// Words of War — Source Data
// Edit this file to update the timeline and statistics.
// Each timeline entry supports:
//   date     (required) — ISO date string "YYYY-MM-DD"
//   quote    (required) — the primary statement
//   context  (optional) — a plain-text explanatory line
//   extra    (optional) — a secondary italicized quote fragment
//   source   (required) — label for the source (e.g. "Reuters", "Truth Social")
//   link     (required) — URL to the original source
//   reaction (optional) — filename to display below the source link

const data = [
  {
    date: "2026-03-11", quote: "You never like to say too early you won. We won. In the first hour it was over.", source: "Reuters", link: "https://www.reuters.com/world/iran-war-live-tehran-continues-fire-israel-targets-across-middle-east-2026-03-11/", reaction: "will-ferrell-anchorman-dont-believe.gif"
  },
  { date: "2026-03-17", quote: "very foolish mistake", context: "Trump said NATO\u2019s refusal to help was a \u2018very foolish mistake.\u2019", source: "Reuters", link: "https://www.reuters.com/world/middle-east/nato-countries-dont-want-get-involved-iran-operation-trump-says-2026-03-17/", reaction: "donald-trump-yuge.gif" },
  { date: "2026-03-20", quote: "Without the U.S.A., NATO IS A PAPER TIGER!", extra: "Militarily WON", source: "Truth Social", link: "https://truthsocial.com/@realDonaldtrump/posts/116261796648776538", reaction: "peggy-big-hair.gif" },
  { date: "2026-03-24", quote: "making progress", context: "Trump said the U.S. was making progress toward ending the war and was talking to \u2018the right people\u2019 in Iran.", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/iran-sends-waves-missiles-into-israel-dismisses-trumps-talk-negotiations-fake-2026-03-24/", reaction: "stanley-hudson.gif" },
  { date: "2026-03-24", quote: "They gave us a present and the ⁠present arrived today, and it was a very big present, ​worth a tremendous amount of money.", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/trump-us-is-talking-right-people-iran-says-tehran-badly-wants-deal-2026-03-24/", reaction: "succession-logan-roy-not-serious-people.gif" },
  { date: "2026-03-31", quote: "We\u2019ll be leaving very soon", extra: "within two weeks, maybe two weeks, maybe three", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-could-end-war-in-iran-two-three-weeks-2026-03-31/", reaction: "trump-concepts-of-plan.gif" },
  { date: "2026-03-31", quote: "some delayed courage, go to the strait and just TAKE IT", context: "Trump said countries hurt by the Strait of Hormuz closure should go take it.", source: "Reuters", link: "https://www.reuters.com/business/energy/giant-oil-tanker-off-dubai-hit-by-iranian-strike-trump-threatens-obliterate-iran-2026-03-31/", reaction: "shocked-surprised.gif" },
  { date: "2026-04-02", quote: "We are going to hit them extremely hard over the next two to three weeks. We are going to bring them back to the Stone Ages, where they belong.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-threatens-strike-irans-bridges-electric-power-plants-2026-04-03/", reaction: "will-ferrell-anchorman-escalated-quickly.gif" },
  { date: "2026-04-02", quote: "[The U.S. military] hasn\u2019t even started destroying what\u2019s left in Iran. Bridges next, then Electric Power Plants.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-threatens-strike-irans-bridges-electric-power-plants-2026-04-03/" },
  { date: "2026-04-05", quote: "Tuesday will be Power Plant Day, and Bridge Day, all wrapped up in one, in Iran. There will be nothing like it!!!", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-target-irans-infrastructure-tuesday-2026-04-05/", reaction: "this-is-all-a-little-intense-alexis-rose.gif" },
  { date: "2026-04-05", quote: "Open the Fuckin\u2019 Strait, you crazy bastards, or you\u2019ll be living in Hell \u2014 JUST WATCH!", extra: "Praise be to Allah.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-target-irans-infrastructure-tuesday-2026-04-05/", reaction: "crazy-trump.gif" },
  { date: "2026-04-05", quote: "The rescue was an Easter Miracle.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-target-irans-infrastructure-tuesday-2026-04-05/" },
  { date: "2026-04-05", quote: "we\u2019re blowing up the whole country", context: "On ABC, Trump said that if the conflict did not end quickly, \u2018we\u2019re blowing up the whole country,\u2019 and that there was \u2018very little\u2019 off the table.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-target-irans-infrastructure-tuesday-2026-04-05/", reaction: "iasip-nope.gif" },
  { date: "2026-04-06", quote: "They made a proposal, and it\u2019s a significant proposal. It\u2019s a significant step. It\u2019s not good enough.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-tuesday-deadline-make-deal-with-iran-is-final-2026-04-06/", reaction: "arrested-development-expected.gif" },
  { date: "2026-04-06", quote: "I\u2019m not worried about it. You know what\u2019s a war crime? Having a nuclear weapon.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-tuesday-deadline-make-deal-with-iran-is-final-2026-04-06/" },
  { date: "2026-04-06", quote: "At the end of 10, all hell\u2019s going to break out if you don\u2019t get there.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-tuesday-deadline-make-deal-with-iran-is-final-2026-04-06/" },
  { date: "2026-04-06", quote: "Well they should do it but, again, the consequences are great. I mean, they were told, \u2018If you protest, you will be shot immediately.\u2019", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-iranians-should-rise-up-against-government-if-ceasefire-declared-2026-04-06/" },
  { date: "2026-04-06", quote: "taken out", context: "Reuters reported Trump said Iran could be \u2018taken out\u2019 if no deal was reached by Tuesday night.", source: "Reuters", link: "https://www.reuters.com/world/us/trump-says-iran-could-be-taken-out-tuesday-night-2026-04-06/" },
  { date: "2026-04-07", quote: "A whole civilization will die tonight, never to be brought back again. I don\u2019t want that to happen, but it probably will.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-a-whole-civilization-will-die-tonight-if-iran-does-not-make-deal-2026-04-07/", reaction: "this-is-fine.gif" },
  { date: "2026-04-08", quote: "We're thinking of doing it as a joint venture. It's a way of securing it — also securing it from lots of other people.", context: "Trump was discussing a possible U.S.-Iran joint arrangement involving security and access in the Strait of Hormuz.", source: "Reuters", link: "https://www.reuters.com/world/us/trump-pushes-strait-hormuz-reopening-without-tolls-white-house-says-2026-04-08/", reaction: "trump-epstein.gif" },
  { date: "2026-04-10", quote: "It won't be easy ... we will have that open fairly soon.", context: "Trump said the U.S. would get the Strait of Hormuz reopened and that other countries would help.", source: "Reuters", link: "https://www.reuters.com/business/energy/trump-says-us-will-have-strait-hormuz-open-fairly-soon-2026-04-10/", reaction: "arrested-development-season1-huge-mistake.gif" },
  { date: "2026-04-12", quote: "Any Iranian who fires at us, or at peaceful vessels, will be BLOWN TO HELL!", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/us-iran-talks-pause-now-disagreements-remain-2026-04-11/" },
  { date: "2026-04-13", quote: "immediately ELIMINATED", context: "Trump said ships approaching the U.S. blockade of Iranian ports would be ‘immediately ELIMINATED.’", source: "AP", link: "https://apnews.com/article/iran-us-israel-trump-lebanon-blockade-hormuz-april-13-2026-ed7a6cd4bc61dc47f317a2c82afcc1c9" },
  { date: "2026-04-17", quote: "remain in full force and effect... until... our transaction with Iran is 100% complete.", context: "Trump said the blockade of Iran would remain in place until a negotiated agreement was complete.", source: "Reuters", link: "https://www.reuters.com/world/trump-says-blockade-iran-in-full-force-until-deal-is-reached-2026-04-17/" },
  { date: "2026-04-18", quote: "The main thing is that Iran will not have a nuclear weapon... and that supersedes everything else.", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/trump-says-he-has-good-news-iran-no-clarity-peace-deal-2026-04-18/" },
  { date: "2026-04-29", quote: "They don't know how to sign a non-nuclear deal. They'd better get smart soon!", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/trump-urges-iran-sign-deal-after-report-suggests-us-may-extend-blockade-2026-04-29/" },
  { date: "2026-05-07", quote: "They trifled with us today. We blew them away.", context: "Trump was describing U.S. strikes against Iran while saying the ceasefire still existed.", source: "Reuters", link: "https://www.reuters.com/world/china/trump-sees-swift-end-war-iran-reviews-us-peace-proposal-2026-05-07/", reaction: "wolf-of-wall-street-the-show-goes-on.gif" },
  { date: "2026-05-11", quote: "life support", context: "Trump said the ceasefire with Iran was on ‘life support’ while criticizing Iran’s latest proposal.", extra: "that piece of garbage they sent us", source: "AP", link: "https://apnews.com/article/iran-us-israel-china-war-may-11-2026-0e9067769efea20e9d45e3d43158ad8c", reaction: "trump-fry.gif" },
  { date: "2026-05-20", quote: "Either have a deal or we're going to do some things that are a little bit nasty...", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/tankers-exit-hormuz-trump-vance-talk-up-iran-deal-prospects-2026-05-20/" },
  { date: "2026-05-24", quote: "remain in full force and effect until an agreement is reached, certified, and signed.", context: "Trump said the blockade would remain until an Iran agreement was formally completed.", source: "Reuters", link: "https://www.reuters.com/world/us/trump-says-iran-deal-largely-negotiated-dispute-over-strait-reopening-2026-05-24/" },
  { date: "2026-05-27", quote: "Nobody's going to control [the strait]. It's international waters.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/iran-could-open-strait-hormuz-within-month-if-terms-agreed-state-tv-says-2026-05-27/" },
  { date: "2026-05-29", quote: "Iran must agree that they will never have a Nuclear Weapon or Bomb. The Hormuz Strait must be immediately open...", source: "Reuters", link: "https://www.reuters.com/world/middle-east/iran-calls-actions-not-words-after-us-officials-say-peace-deal-is-near-2026-05-29/" },
  { date: "2026-06-01", quote: "Talks are continuing, at a rapid pace, with the Islamic Republic of Iran.", context: "Earlier the same day, Trump had dismissed the possibility that talks were over.", extra: "I couldn't care less", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-he-has-not-heard-iran-that-they-are-suspending-talks-nbc-news-reports-2026-06-01/", reaction: "war-dogs-war-dogs-i-guess-bro.gif" },
  { date: "2026-06-10", quote: "have to pay the price", context: "Trump said Iran would ‘have to pay the price’ and that the U.S. would attack Iran ‘very hard’ without a peace deal.", extra: "very hard", source: "Reuters", link: "https://www.reuters.com/business/energy/oil-rises-nearly-1-us-launches-new-strikes-against-iran-supply-tightens-2026-06-10/", reaction: "math-calculator.gif" },
  { date: "2026-06-11", quote: "We just made a great settlement of the war with Iran.", source: "Reuters", link: "https://www.reuters.com/world/trump-says-great-settlement-iran-be-signed-soon-strait-will-open-2026-06-11/", reaction: "shark-tank-mr-wonderful-deal.gif" },
  { date: "2026-06-21", quote: "If they don't, we'll hit Iran very hard again, just like we did last week, only harder!!!", context: "Trump said the U.S. would resume attacks if Iran did not restrain Hezbollah and allied groups.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-resume-attacks-if-iran-does-not-restrain-hezbollah-allies-2026-06-21/", reaction: "thats-what-she-said.gif" },
  { date: "2026-07-06", quote: "We're either going to make a deal or we're going to finish the job.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-there-will-either-be-deal-with-iran-or-us-will-finish-job-2026-07-06/", reaction: "whatever-trump.gif" },
  { date: "2026-07-08", quote: "To me, I think it's over. I don't want to deal with them.", context: "Trump was referring to the interim agreement with Iran as fresh strikes began.", source: "Reuters", link: "https://www.reuters.com/world/europe/trump-says-interim-accord-with-iran-end-war-is-over-2026-07-08/", reaction: "shark-tank-mr-wonderful-no-deal-nope.gif" },
  { date: "2026-07-13", quote: "We're going to keep the strait, and we'll probably run it. We'll become the guardian of the strait.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-will-control-strait-hormuz-get-paid-it-2026-07-13/", reaction: "schitts-creek-mmhmm-okay.gif" },
  { date: "2026-07-20", quote: "is gonna pay a big price", context: "Trump said Iran was ‘gonna pay a big price’ following the deaths of U.S. service members.", source: "AP", link: "https://apnews.com/article/dignified-transfer-iran-war-trump-8a79b27e10cedd202596d57f743ca569" },
  { date: "2026-07-22", quote: "will bomb and destroy ONE BRIDGE OR POWER PLANT", context: "Trump said the U.S. would destroy one Iranian bridge or power plant each time Iran attacked a ship in the Strait of Hormuz.", source: "Reuters", link: "https://www.reuters.com/world/trump-us-will-attack-iranian-bridge-power-plant-every-ship-targeted-hormuz-2026-07-22/", reaction: "succession-poor-kendall.gif" },
  { date: "2026-07-27", quote: "You can't bribe them. You've got to beat them, and we'll beat the hell out of them.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/iran-says-it-still-controls-strait-not-seeking-talks-after-trump-halts-bombing-2026-07-27/", reaction: "arrested-development-money.gif" },
  { date: "2026-08-01", quote: "I have agreed... to cancel the attack, subject to being able to rapidly make a DEAL.", source: "Reuters", link: "https://www.reuters.com/world/asia-pacific/iran-threatens-strike-other-nations-energy-fields-if-us-launches-fresh-attacks-2026-08-01/", reaction: "dj-khaled-another-one.gif" },
  { date: "2026-08-03", quote: "I want to give them every last chance before decapitation.", context: "Trump was threatening a major attack on Iran if negotiations failed to produce a deal.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-talks-with-iran-are-going-right-now-2026-08-03/", reaction: "succession-time-for-a-sacrifice.gif" },
  { date: "2026-08-05", quote: "I'd rather make a deal because I don't want to kill people... but at some point we're gonna.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/us-iran-having-very-good-discussions-trump-says-2026-08-05/" },
  { date: "2026-08-09", quote: "We are low keying it. We are only semi-negotiating with them.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-us-is-low-keying-it-with-iran-stresses-economic-pain-according-axios-2026-08-09/", reaction: "confused-confused-look.gif" },
  { date: "2026-08-10", quote: "We're going to ask for money for the damage they've done over a 50-year period.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/iran-ties-hormuz-reopening-us-concessions-several-demands-2026-08-09/", reaction: "leonardo-dicaprio-sell-me-this-pen.gif" },
  { date: "2026-08-11", quote: "Hit them really, really hard.", context: "Trump described another major attack as one of the U.S. options for dealing with Iran.", source: "Reuters", link: "https://www.reuters.com/world/middle-east/trump-says-iran-options-are-let-tehran-fail-economically-or-hit-them-really-hard-2026-08-11/", reaction: "arrested-development-blue.gif" },
  { date: "2026-08-12", quote: "The U.S.A. has total control over the Strait of Hormuz. I THINK WE WILL KEEP IT!", source: "Reuters", link: "https://www.reuters.com/world/trump-says-us-has-total-control-over-strait-hormuz-2026-08-12/", reaction: "im-not-leaving-wolf-of-wall-street.gif" },
  { date: "2026-08-14", quote: "After we finish defeating Iran ... pretty soon I'll be declaring the Hormuz Strait a territory of the United States.", source: "Reuters", link: "https://www.reuters.com/world/us/trump-urges-americans-accept-higher-gas-prices-he-escalates-iran-rhetoric-2026-08-14/", reaction: "the-office-bankruptcy.gif" }
];

// TL;DR summary rendered above the timeline.
const summaryData = [
  "Trump’s stated rationale for the war has repeatedly shifted: stop Iran’s nuclear program → declare victory → force a deal → reopen the Strait of Hormuz → punish Iran for resisting → threaten regime change and broader destruction.",
  "His position on Hormuz has shifted just as dramatically: international waters → U.S.-managed waterway → U.S.-controlled waterway → claimed U.S. territory.",
  "Taken together, the timeline shows the war’s stated purpose expanding over time: prevent a nuclear threat → compel a settlement → own the strategic waterway at the center of the conflict."
];

// Featured pull-quote rendered in the large centered block.
const featuredRaw = "We are going to bring them back to the Stone Ages, where they belong.";

// "By the numbers" statistics grid.
const statsData = [
  { num: '50', label: 'Verified Statements' },
  { num: '157', label: 'Days Documented' },
  { num: '46', label: 'Reuters Sources' },
  { num: '4', label: 'Other Sources' },
];
